In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data_sets/data.csv')
df.head()

Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [5]:
print(df.isnull().sum())
df.fillna(250, inplace=True)
print(df.isnull().sum())

Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64
Duration    0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64


In [6]:
df.describe()

Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   169.000000
mean    63.846154  107.461538  134.047337   372.068639
std     42.299949   14.510259   16.450434   263.255396
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.000000
50%     60.000000  105.000000  131.000000   310.200000
75%     60.000000  111.000000  141.000000   384.000000
max    300.000000  159.000000  184.000000  1860.400000

In [8]:
# Get records where calories is > mean
new_df = df[df.Calories > df.Calories.mean()]
print(df.shape, new_df.shape)

(169, 4) (50, 4)


In [27]:
df = pd.read_csv('../data_sets/data.csv')
new_df = df.dropna(inplace=False)
print(new_df.shape, df.shape)

# Replace null calories with 100
df.Calories.fillna(50, inplace=True)
print(df.shape, df.isnull().sum())

(164, 4) (169, 4)
(169, 4) Duration    0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64


In [29]:
# Check for duplicates.
print(df.duplicated())
new_df = df.drop_duplicates(inplace=False)
print(df.shape, new_df.shape)

0      False
1      False
2      False
3      False
4      False
       ...  
164    False
165    False
166    False
167    False
168    False
Length: 169, dtype: bool
(169, 4) (162, 4)


In [31]:
df = pd.read_csv('../data_sets/nba.csv')
df.head()

Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   

             College     Salary  
0              Texas  7730337.0  
1          Marquette  6796117.0  
2  Boston University        NaN  
3      Georgia State  1148640.0  
4                NaN  5000000.0

In [32]:
# Check for how many null values there are in all columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      457 non-null    object 
 1   Team      457 non-null    object 
 2   Number    457 non-null    float64
 3   Position  457 non-null    object 
 4   Age       457 non-null    float64
 5   Height    457 non-null    object 
 6   Weight    457 non-null    float64
 7   College   373 non-null    object 
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB


In [33]:
df.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [35]:
new_df = df.dropna()
print(new_df.shape, df.shape)

(364, 9) (458, 9)


In [41]:
# Encoding of categorical data for simplyfing data processing.
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
df.Name = label_encoder.fit_transform(df.Name)
df.Name

0       34
1      171
2      211
3      355
4      216
      ... 
453    395
454    361
455    417
456    194
457    457
Name: Name, Length: 458, dtype: int64

In [44]:
df.College = label_encoder.fit_transform(df.College)
df.drop('Height', inplace=True, axis=1)

In [45]:
df.head()

Name            Team  Number Position   Age  Weight  College     Salary
0    34  Boston Celtics     0.0       PG  25.0   180.0       93  7730337.0
1   171  Boston Celtics    99.0       SF  25.0   235.0       52  6796117.0
2   211  Boston Celtics    30.0       SG  27.0   205.0        8        NaN
3   355  Boston Celtics    28.0       SG  22.0   185.0       33  1148640.0
4   216  Boston Celtics     8.0       PF  29.0   231.0      118  5000000.0

In [58]:
# Using ordinal encoding for the positions
one_hot_encoder = preprocessing.OneHotEncoder()

# note : one hot encoding needs double bracket when specifying which column it has to chose.
one_hot_encoder = one_hot_encoder.fit_transform(df[['Team']]).toarray()
col = pd.DataFrame(one_hot_encoder)
df = pd.concat([df, col], axis=1)
df.drop(['Team'], axis=1, inplace=True)
df.head()

Name  Number Position   Age  Weight  College     Salary    0    1    2  \
0    34     0.0       PG  25.0   180.0       93  7730337.0  0.0  1.0  0.0   
1   171    99.0       SF  25.0   235.0       52  6796117.0  0.0  1.0  0.0   
2   211    30.0       SG  27.0   205.0        8        NaN  0.0  1.0  0.0   
3   355    28.0       SG  22.0   185.0       33  1148640.0  0.0  1.0  0.0   
4   216     8.0       PF  29.0   231.0      118  5000000.0  0.0  1.0  0.0   

   ...   21   22   23   24   25   26   27   28   29   30  
0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 131 columns]

In [74]:
# Feature scaling
from sklearn.preprocessing import MinMaxScaler
array = pd.DataFrame([233, 100.5, 0.5, 50.0, 25.0, 75.0, 0.0, 1.0])

scaler = MinMaxScaler(feature_range=(0,1))
rescaled_x = scaler.fit_transform(array)
rescaled_x

array([[1.        ],
       [0.43133047],
       [0.00214592],
       [0.21459227],
       [0.10729614],
       [0.32188841],
       [0.        ],
       [0.00429185]])

In [71]:
# Standard scaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler = scaler.fit_transform(array)
scaler

array([[ 2.02075447],
       [ 0.26309604],
       [-1.06343862],
       [-0.40680396],
       [-0.73843763],
       [-0.0751703 ]])

In [75]:
# Normalizer
from sklearn.preprocessing import Normalizer
scaler = Normalizer()

scaler = scaler.fit_transform(array)
scaler

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.]])

In [78]:
# Binarizing data
from sklearn.preprocessing import Binarizer
bin = Binarizer(threshold=75)
bin = bin.fit_transform(array)
bin

array([[1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [82]:
# Splitting the data into train test set.
from sklearn.model_selection import train_test_split

x = [1, 2, 3, 4, 5, 6, 7]
y = [1, 4, 9, 16, 25, 36, 49]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30)
print(x_train, x_test)

[6, 2, 5, 7] [4, 3, 1]
