Classifiers

Question 5. Perpare a classifier model for wine data set

In [97]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import seaborn as sns
import pandas as pd

from sklearn import neighbors
from sklearn import naive_bayes
from sklearn.linear_model import Perceptron

import scipy.stats as stats
import math

In [98]:
df = pd.read_csv('../data_sets/wine.csv')
df

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0       1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1       1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2       1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3       1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4       1    13.24        2.59  2.87  21.0  118     2.80        2.69   
..    ...      ...         ...   ...   ...  ...      ...         ...   
173     3    13.71        5.65  2.45  20.5   95     1.68        0.61   
174     3    13.40        3.91  2.48  23.0  102     1.80        0.75   
175     3    13.27        4.28  2.26  20.0  120     1.59        0.69   
176     3    13.17        2.59  2.37  20.0  120     1.65        0.68   
177     3    14.13        4.10  2.74  24.5   96     2.05        0.76   

     Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                    0.28     2.29       5.64  1.04  3.92     1065  
1                    0.26     1.28       4.38  1.05  3.40     1050  
2                    0.30     2.81       5.68  1.03  3.17     1185  
3                    0.24     2.18       7.80  0.86  3.45     1480  
4                    0.39     1.82       4.32  1.04  2.93      735  
..                    ...      ...        ...   ...   ...      ...  
173                  0.52     1.06       7.70  0.64  1.74      740  
174                  0.43     1.41       7.30  0.70  1.56      750  
175                  0.43     1.35      10.20  0.59  1.56      835  
176                  0.53     1.46       9.30  0.60  1.62      840  
177                  0.56     1.35       9.20  0.61  1.60      560  

[178 rows x 14 columns]

In [99]:
# Use KNN classifier

x = df.iloc[:,1:-1].values
y = df.iloc[:,0]
print("Target : \n", y)

Target : 
 0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: Wine, Length: 178, dtype: int64


In [100]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from matplotlib import pyplot as plt
import seaborn as sb
from sklearn.model_selection import train_test_split

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=4000)

from sklearn.neighbors import KNeighborsClassifier
cl = KNeighborsClassifier(n_neighbors=5, p=3)
cl.fit(x_train, y_train)

y_pred = cl.predict(x_test)
print('Y prediction : ', y_pred)

print("Y test", y_test)

Y prediction :  [2 1 2 3 2 1 1 2 1 2 3 3 2 2 3 3 2 1 1 1 3 2 1 3 2 1 1 2 1 1 3 2 2 1 2 2]
Y test 85     2
61     2
37     1
132    3
127    2
112    2
121    2
67     2
27     1
126    2
158    3
64     2
170    3
111    2
70     2
152    3
94     2
43     1
5      1
31     1
159    3
65     2
95     2
172    3
113    2
29     1
6      1
128    2
49     1
73     2
157    3
109    2
80     2
96     2
129    2
114    2
Name: Wine, dtype: int64


In [101]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix : ", cm)

from sklearn.metrics import accuracy_score
print("accuracy_score : ", accuracy_score(y_test, y_pred))

Confusion matrix :  [[ 7  1  0]
 [ 6 13  2]
 [ 0  1  6]]
accuracy_score :  0.722222222222


In [102]:
# Use Logistic regression classifier.

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

scaler = preprocessing.StandardScaler().fit(x_train)
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

model = LogisticRegression()
model.fit(x_train_scaled, y_train)

train_acc = model.score(x_train_scaled, y_train)
print("Accuracy for training set : ", train_acc * 100)

y_pred = model.predict(x_test_scaled)
test_acc = accuracy_score(y_test, y_pred)
print("Accuracy for test set : ", test_acc * 100)

print(classification_report(y_test, y_pred))

c_mat = confusion_matrix(y_test, y_pred)
print("Confusion matrix:\n", c_mat)

print("accuracy_score : ", accuracy_score(y_test, y_pred))

Accuracy for training set :  100.0
Accuracy for test set :  97.2222222222
              precision    recall  f1-score   support

           1       0.91      1.00      0.95        10
           2       1.00      0.92      0.96        13
           3       1.00      1.00      1.00        13

    accuracy                           0.97        36
   macro avg       0.97      0.97      0.97        36
weighted avg       0.97      0.97      0.97        36

Confusion matrix:
 [[10  0  0]
 [ 1 12  0]
 [ 0  0 13]]
accuracy_score :  0.972222222222


Use Perceptron Classifier

In [103]:
p_classifier = Perceptron(tol=1e-3, random_state=1)
p_classifier.fit(x, y)
print("Score using Perceptron classifier : ", p_classifier.score(x, y))


Score using Perceptron classifier :  0.679775280899


Q4-Consider the Chronic Kidney Disease (CKD) data. Prepare a classifier model as stated above.  Given that a new patient Alice has Haemoglobin 0 and Glucose levels 1.1 standard deviations above average, find if Alice is likely to have CKD. 

In [104]:
df = pd.read_csv('../data_sets/ckd.csv')
df

Age  Blood Pressure  Specific Gravity  Albumin  Sugar Red Blood Cells  \
0     48              70             1.005        4      0          normal   
1     53              90             1.020        2      0        abnormal   
2     63              70             1.010        3      0        abnormal   
3     68              80             1.010        3      2          normal   
4     61              80             1.015        2      0        abnormal   
..   ...             ...               ...      ...    ...             ...   
153   55              80             1.020        0      0          normal   
154   42              70             1.025        0      0          normal   
155   12              80             1.020        0      0          normal   
156   17              60             1.025        0      0          normal   
157   58              80             1.025        0      0          normal   

     Pus Cell Pus Cell clumps    Bacteria  Blood Glucose Random  ...  \
0    abnormal         present  notpresent                   117  ...   
1    abnormal         present  notpresent                    70  ...   
2    abnormal         present  notpresent                   380  ...   
3    abnormal         present     present                   157  ...   
4    abnormal      notpresent  notpresent                   173  ...   
..        ...             ...         ...                   ...  ...   
153    normal      notpresent  notpresent                   140  ...   
154    normal      notpresent  notpresent                    75  ...   
155    normal      notpresent  notpresent                   100  ...   
156    normal      notpresent  notpresent                   114  ...   
157    normal      notpresent  notpresent                   131  ...   

     Packed Cell Volume  White Blood Cell Count  Red Blood Cell Count  \
0                    32                    6700                   3.9   
1                    29                   12100                   3.7   
2                    32                    4500                   3.8   
3                    16                   11000                   2.6   
4                    24                    9200                   3.2   
..                  ...                     ...                   ...   
153                  47                    6700                   4.9   
154                  54                    7800                   6.2   
155                  49                    6600                   5.4   
156                  51                    7200                   5.9   
157                  53                    6800                   6.1   

     Hypertension  Diabetes Mellitus  Coronary Artery Disease  Appetite  \
0             yes                 no                       no      poor   
1             yes                yes                       no      poor   
2             yes                yes                       no      poor   
3             yes                yes                      yes      poor   
4             yes                yes                      yes      poor   
..            ...                ...                      ...       ...   
153            no                 no                       no      good   
154            no                 no                       no      good   
155            no                 no                       no      good   
156            no                 no                       no      good   
157            no                 no                       no      good   

     Pedal Edema Anemia Class  
0            yes    yes     1  
1             no    yes     1  
2            yes     no     1  
3            yes     no     1  
4            yes    yes     1  
..           ...    ...   ...  
153           no     no     0  
154           no     no     0  
155           no     no     0  
156           no     no     0  
157           no     no     0  

[158 rows x 25 columns]

In [105]:
from datascience import *

table = Table.read_table('../data_sets/ckd.csv').relabeled('Blood Glucose Random', 'Glucose')
table

Age  | Blood Pressure | Specific Gravity | Albumin | Sugar | Red Blood Cells | Pus Cell | Pus Cell clumps | Bacteria   | Glucose | Blood Urea | Serum Creatinine | Sodium | Potassium | Hemoglobin | Packed Cell Volume | White Blood Cell Count | Red Blood Cell Count | Hypertension | Diabetes Mellitus | Coronary Artery Disease | Appetite | Pedal Edema | Anemia | Class
48   | 70             | 1.005            | 4       | 0     | normal          | abnormal | present         | notpresent | 117     | 56         | 3.8              | 111    | 2.5       | 11.2       | 32                 | 6700                   | 3.9                  | yes          | no                | no                      | poor     | yes         | yes    | 1
53   | 90             | 1.02             | 2       | 0     | abnormal        | abnormal | present         | notpresent | 70      | 107        | 7.2              | 114    | 3.7       | 9.5        | 29                 | 12100                  | 3.7                  | yes          | yes               | no                      | poor     | no          | yes    | 1
63   | 70             | 1.01             | 3       | 0     | abnormal        | abnormal | present         | notpresent | 380     | 60         | 2.7              | 131    | 4.2       | 10.8       | 32                 | 4500                   | 3.8                  | yes          | yes               | no                      | poor     | yes         | no     | 1
68   | 80             | 1.01             | 3       | 2     | normal          | abnormal | present         | present    | 157     | 90         | 4.1              | 130    | 6.4       | 5.6        | 16                 | 11000                  | 2.6                  | yes          | yes               | yes                     | poor     | yes         | no     | 1
61   | 80             | 1.015            | 2       | 0     | abnormal        | abnormal | notpresent      | notpresent | 173     | 148        | 3.9              | 135    | 5.2       | 7.7        | 24                 | 9200                   | 3.2                  | yes          | yes               | yes                     | poor     | yes         | yes    | 1
48   | 80             | 1.025            | 4       | 0     | normal          | abnormal | notpresent      | notpresent | 95      | 163        | 7.7              | 136    | 3.8       | 9.8        | 32                 | 6900                   | 3.4                  | yes          | no                | no                      | good     | no          | yes    | 1
69   | 70             | 1.01             | 3       | 4     | normal          | abnormal | notpresent      | notpresent | 264     | 87         | 2.7              | 130    | 4         | 12.5       | 37                 | 9600                   | 4.1                  | yes          | yes               | yes                     | good     | yes         | no     | 1
73   | 70             | 1.005            | 0       | 0     | normal          | normal   | notpresent      | notpresent | 70      | 32         | 0.9              | 125    | 4         | 10         | 29                 | 18900                  | 3.5                  | yes          | yes               | no                      | good     | yes         | no     | 1
73   | 80             | 1.02             | 2       | 0     | abnormal        | abnormal | notpresent      | notpresent | 253     | 142        | 4.6              | 138    | 5.8       | 10.5       | 33                 | 7200                   | 4.3                  | yes          | yes               | yes                     | good     | no          | no     | 1
46   | 60             | 1.01             | 1       | 0     | normal          | normal   | notpresent      | notpresent | 163     | 92         | 3.3              | 141    | 4         | 9.8        | 28                 | 14600                  | 3.2                  | yes          | yes               | no                      | good     | no          | no     | 1
...

In [106]:
def standard_units(x):
    return (x - np.mean(x))/np.std(x)

Standardize values across columns (to bring quantitative data to same scale)

In [107]:
table = Table().with_columns(
    'Hemoglobin', standard_units(table.column('Hemoglobin')),
    'Glucose', standard_units(table.column('Glucose')),
    'White Blood Cell Count', standard_units(table.column('White Blood Cell Count')),
    'Class', table.column('Class')
)

Checking against the given test case (Alice's Hemoglobin attribute)

In [108]:
# In this example, Alice's Hemoglobin attribute is 0 and her Glucose is 1.5.
alice = make_array(0, 1.5)

# Use KNN classifier

x = df.iloc[:,0:-1].values
y = df['Class']
print("Target : \n", y)

Target : 
 0      1
1      1
2      1
3      1
4      1
      ..
153    0
154    0
155    0
156    0
157    0
Name: Class, Length: 158, dtype: int64


In [109]:
df

Age  Blood Pressure  Specific Gravity  Albumin  Sugar Red Blood Cells  \
0     48              70             1.005        4      0          normal   
1     53              90             1.020        2      0        abnormal   
2     63              70             1.010        3      0        abnormal   
3     68              80             1.010        3      2          normal   
4     61              80             1.015        2      0        abnormal   
..   ...             ...               ...      ...    ...             ...   
153   55              80             1.020        0      0          normal   
154   42              70             1.025        0      0          normal   
155   12              80             1.020        0      0          normal   
156   17              60             1.025        0      0          normal   
157   58              80             1.025        0      0          normal   

     Pus Cell Pus Cell clumps    Bacteria  Blood Glucose Random  ...  \
0    abnormal         present  notpresent                   117  ...   
1    abnormal         present  notpresent                    70  ...   
2    abnormal         present  notpresent                   380  ...   
3    abnormal         present     present                   157  ...   
4    abnormal      notpresent  notpresent                   173  ...   
..        ...             ...         ...                   ...  ...   
153    normal      notpresent  notpresent                   140  ...   
154    normal      notpresent  notpresent                    75  ...   
155    normal      notpresent  notpresent                   100  ...   
156    normal      notpresent  notpresent                   114  ...   
157    normal      notpresent  notpresent                   131  ...   

     Packed Cell Volume  White Blood Cell Count  Red Blood Cell Count  \
0                    32                    6700                   3.9   
1                    29                   12100                   3.7   
2                    32                    4500                   3.8   
3                    16                   11000                   2.6   
4                    24                    9200                   3.2   
..                  ...                     ...                   ...   
153                  47                    6700                   4.9   
154                  54                    7800                   6.2   
155                  49                    6600                   5.4   
156                  51                    7200                   5.9   
157                  53                    6800                   6.1   

     Hypertension  Diabetes Mellitus  Coronary Artery Disease  Appetite  \
0             yes                 no                       no      poor   
1             yes                yes                       no      poor   
2             yes                yes                       no      poor   
3             yes                yes                      yes      poor   
4             yes                yes                      yes      poor   
..            ...                ...                      ...       ...   
153            no                 no                       no      good   
154            no                 no                       no      good   
155            no                 no                       no      good   
156            no                 no                       no      good   
157            no                 no                       no      good   

     Pedal Edema Anemia Class  
0            yes    yes     1  
1             no    yes     1  
2            yes     no     1  
3            yes     no     1  
4            yes    yes     1  
..           ...    ...   ...  
153           no     no     0  
154           no     no     0  
155           no     no     0  
156           no     no     0  
157           no     no     0  

[158 rows x 25 columns]

In [110]:
import sklearn.preprocessing

enc = sklearn.preprocessing.OrdinalEncoder()

enc.fit(df[["Sugar", "Red Blood Cells","Pus Cell", "Pus Cell clumps", "Blood Glucose Random", "Bacteria", "Hypertension", "Diabetes Mellitus", "Coronary Artery Disease", "Appetite", "Pedal Edema", "Anemia"]])  
df[["Sugar", "Red Blood Cells","Pus Cell", "Pus Cell clumps", "Blood Glucose Random", "Bacteria", "Hypertension", "Diabetes Mellitus", "Coronary Artery Disease", "Appetite", "Pedal Edema", "Anemia",]] = enc.transform(df[["Sugar", "Red Blood Cells","Pus Cell", "Pus Cell clumps", "Blood Glucose Random", "Bacteria", "Hypertension", "Diabetes Mellitus", "Coronary Artery Disease", "Appetite", "Pedal Edema", "Anemia",]])

In [127]:
df

df.to_csv('../data_sets/modified_ckd.csv')

df = df[['Blood Glucose Random', 'Hemoglobin', 'Class']]
print(df)
x = df.iloc[:,0:-1].values
y = df['Class']

print(x)

     Blood Glucose Random  Hemoglobin  Class
0                    36.0        11.2      1
1                     0.0         9.5      1
2                    75.0        10.8      1
3                    56.0         5.6      1
4                    58.0         7.7      1
..                    ...         ...    ...
153                  55.0        15.7      0
154                   2.0        16.5      0
155                  24.0        15.8      0
156                  35.0        14.2      0
157                  49.0        15.8      0

[158 rows x 3 columns]
[[ 36.   11.2]
 [  0.    9.5]
 [ 75.   10.8]
 [ 56.    5.6]
 [ 58.    7.7]
 [ 19.    9.8]
 [ 69.   12.5]
 [  0.   10. ]
 [ 67.   10.5]
 [ 57.    9.8]
 [ 47.    9.1]
 [ 51.   10.3]
 [  3.    7.1]
 [ 71.   13. ]
 [ 60.   16.1]
 [ 62.   10.4]
 [ 73.    9.2]
 [ 37.   11.4]
 [ 63.    8.1]
 [ 46.    8.2]
 [ 37.   12. ]
 [ 27.   11.1]
 [ 72.    7.9]
 [ 70.    8.3]
 [ 41.   12.6]
 [ 74.   10.4]
 [ 25.    8.7]
 [ 29.    8.3]
 [ 36.   10. ]
 

In [112]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from matplotlib import pyplot as plt
import seaborn as sb
from sklearn.model_selection import train_test_split

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=4000)


from sklearn.neighbors import KNeighborsClassifier
cl = KNeighborsClassifier(n_neighbors=5, p=3)
cl.fit(x_train, y_train)

y_pred = cl.predict(x_test)
print('Y prediction : ', y_pred)

print("Y test", y_test)

Y prediction :  [0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0]
Y test 122    0
125    0
105    0
140    0
86     0
27     1
65     0
144    0
6      1
152    0
153    0
116    0
95     0
101    0
64     0
55     0
92     0
44     0
113    0
29     1
49     0
37     1
130    0
80     0
73     0
69     0
22     1
47     0
139    0
134    0
108    0
146    0
Name: Class, dtype: int64


In [122]:
from sklearn.neighbors import KNeighborsClassifier
cl = KNeighborsClassifier(n_neighbors=3, p=2)
cl.fit(x_train, y_train)

y_pred = cl.predict(x_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[27,  0],
       [ 0,  5]], dtype=int64)

In [114]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix : ", cm)

from sklearn.metrics import accuracy_score
print("accuracy_score : ", accuracy_score(y_test, y_pred))

Confusion matrix :  [[27  0]
 [ 0  5]]
accuracy_score :  1.0


Testing against given input

In [115]:
alice = make_array(0, 1.5)

In [116]:
def distance(point1, point2):
    return np.sqrt(np.sum((point1 - point2)**2))

In [117]:
def distance_from_alice(row):    return (alice, np.array(row))

In [118]:
df[['Class', 'Hemoglobin', 'Blood Glucose Random']]

Class  Hemoglobin  Blood Glucose Random
0        1        11.2                  36.0
1        1         9.5                   0.0
2        1        10.8                  75.0
3        1         5.6                  56.0
4        1         7.7                  58.0
..     ...         ...                   ...
153      0        15.7                  55.0
154      0        16.5                   2.0
155      0        15.8                  24.0
156      0        14.2                  35.0
157      0        15.8                  49.0

[158 rows x 3 columns]

In [137]:
print("Alice : ", alice)
y_pred = cl.predict(alice.reshape(1,-1))
print(y_pred)

Alice :  [ 0.   1.5]
[1]


In [138]:
if y_pred == 1:
    print("Alice has glucose (very likeley)")
else:
    print("Alice is unlikely to get glucose")

Alice has glucose (very likeley)
