In [12]:
# Importing the numpy library.

import numpy as np


In [4]:
# Q1. Generate a tuple from the set ["aman", "222", 777, 400.4] 
tup = tuple(["aman", "222", 777, 400.4])
print(tup, type(tup))

('aman', '222', 777, 400.4) <class 'tuple'>


In [5]:
# Q2. Create a dictionary of your basic data : (a) Roll No (b) Last Name (c) First Name (d) Date of birth. Print out the values and keys. 
basic_data = { 'roll_no': 'CB.EN.U4CSE20666', 'last_name': 'Ramaswamy', 'first_name': 'Tarun', 'date_of_birth': '09/01/2003'}
for (key) in basic_data:
    print(key, "=>", basic_data[key])

roll_no => CB.EN.U4CSE20666
last_name => Ramaswamy
first_name => Tarun
date_of_birth => 09/01/2003


In [6]:
# Q3. Use rand function to generate a 2-dimensional random array with seed. 
np.random.seed(1234566)
mat = np.random.rand(2, 2)
mat

array([[0.0735006 , 0.33757761],
       [0.64666282, 0.26530724]])

In [7]:
# Q4. Generate a single random number in [0.0, 1.0]. Find the absolute value of (-1234) 
rand_num = np.random.random()
rand_num

print(rand_num, abs(-1234))

0.4020764116303175 1234


In [8]:
# Q5. Return a random integer N such that 20 <= N <= 90.  
rand_num = np.random.randint(20, 90)
rand_num

85

In [9]:
# Q6. Given a population or set[11, 12, 13,14, 15] 
# Return a 3 length list of unique elements without replacement. 
# Shuffle the above set 
# Print a random number from the set 

s = ([11, 12, 13, 14, 15])
print(np.random.choice(s, 3))

print(np.random.shuffle(s))
print(s)

print(np.random.choice(s, 1))

[12 13 15]
None
[14, 12, 13, 11, 15]
[12]


In [10]:
# Q7. Write the text "The King is Dead, Long Live The King" on to a file in your hard drive; read and print the text. 
f = open('../data_sets/c_file.txt', 'w+')
f.write('The King is Dead, Long Live The King!')
f.close()

f = open('../data_sets/c_file.txt', 'r')
f_contents = f.read()
print(f_contents)
f.close()

The King is Dead, Long Live The King!


In [11]:
# Q8. Create an illustrative function to demonstrate use of: if, elif and else (b) for, while, break and continue.

def _sign(x):
    if x < 0:
        return -1
    elif x == 0:
        return 0
    elif x > 0:
        return 1

print(_sign(-199))

for i in range(0, 10):
    print(i)

i = 0
while i < 10:
    print(i)
    i += 1

i = 0
while True:
    if i < 10:
        continue
    elif i == 10:
        break

-1
0
1
2
3
4
5
6
7
8
9
0
1
2
3
4
5
6
7
8
9


KeyboardInterrupt: 

In [ ]:
# Q9. Given a string "The King is Dead, Long Live The King"  
# Print the complete string 
# Print first character of the string 
# Print characters starting from 3rd to 5th 
# Print string starting from 3rd character 
# Split the words 

s = 'The King is Dead, Long Live The King'

print(s)
print(s[0])
print(s[3:6])
print(s[3:])
print(s.split(' '))

The King is Dead, Long Live The King
T
 Ki
 King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


In [15]:
# Q10. An array can be created from a list:  Create an array from a list comprising of numbers 1,4,5,8 (treat them as floats).Slice the above array to display first and second elements 

arr = np.array([1, 4, 5, 8], dtype=np.float32)
arr[0:2]

array([1., 4.], dtype=float32)

In [17]:
# Q11. Arrays can be multidimensional. Create a two-dimensional array of (1,2,3) and (4,5,6). 

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# Q12. Array slicing works with multiple dimensions in the same way as usual, applying each slice specification as a filter to a specified dimension. Consider two-dimensional array of (1,2,3) and (4,5,6). 
# Slice and display the 2nd row. 
# Write code to display as array([2., 5.])  
# Find the length of the array. 

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1:])

print(arr[:,1])

print(len(arr))

[[4 5 6]]
[2 5]
2


In [39]:
# Q13. Arrays can be reshaped using tuples that specify new dimensions. Turn a ten-element one-dimensional array into a two-dimensional one whose first axis has five elements and whose second axis has two elements. Obtain the transpose of the array 

arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr = np.array(arr)

arr = arr.reshape((2, 5))
print(arr)
print(arr.transpose())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [40]:
# Q14. Create an array from a list of 1,2 and 3. 
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [42]:
# Q15. Fill an array [1,2,3] with a single value [9,9,9].  
arr = [1, 2, 3]
arr = np.array(arr)

arr.fill(9)
arr

array([9, 9, 9])

In [43]:
# Q16. Sum the elements of array [2,4,5]. 
arr = np.array([2, 4, 5])
arr.sum()

11

In [44]:
# Q17. Give the products of array [77,74,75] 
arr = np.array([77, 74, 75])
arr.prod()

427350

In [57]:
# Q18. Given an array [2,1,9,1,2,22,1,1,4,55,6,2,56]. Find mean, variance, max, min, argmin, median, argmax and standard deviation. 

arr = np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
arr

print("Mean:", arr.mean())
print("Variance:", arr.var())
print("Max:", arr.max())
print("Min:", arr.min())
print("Argmin:", arr.argmin())
print("Argmax:", arr.argmax())
print("Median:", np.median(arr))
print("SD:", np.std(arr))

Mean: 12.461538461538462
Variance: 367.32544378698225
Max: 56
Min: 1
Argmin: 1
Argmax: 12
Median: 2.0
SD: 19.165736192147232


In [63]:
# Q19. Extract unique elements from an array: [1, 1, 4, 5, 5, 5, 7] and sort it. 
arr = np.array([1, 1, 4, 5, 5, 5, 7])
arr = np.unique(arr)
print(np.sort(arr))

[1 4 5 7]


In [64]:
# Q19. Find dot product of two arrays [1, 2, 3]and [0, 1, 1].
arr1 = np.array([1, 2, 3])
arr2 = np.array([0, 1, 1])
print(np.dot(arr1, arr2))

5


In [69]:
# Q20. Find the eigenvalues and eigenvectors of matrix A. 
# A = [[2, -12], [1, -5]]

a = np.matrix([[2, -12], [1, -5]])
print(np.linalg.eig(a))

(array([-1., -2.]), matrix([[0.9701425 , 0.9486833 ],
        [0.24253563, 0.31622777]]))


In [73]:
# Q21. Given an array with [11, 22, 11, 31], [25, 33, 31, 28]]. Treat as floats. Find the correlation coefficients.
arr = np.array([[11, 22, 11, 31], [25, 33, 31, 28]], dtype=np.float32)
np.corrcoef(arr)

array([[1.        , 0.15997968],
       [0.15997968, 1.        ]])